<definitions name="DistanceService" targetNamespace="http://localhost:8080/distance?wsdl" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://localhost:8080/distance?wsdl" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <message name="distance">
    <part name="distance" type="xsd:int"/>
    <part name="autonomie" type="xsd:int"/>
    <part name="tempschargement" type="xsd:int"/>
  </message>

  <message name="distanceResponse">
    <part name="distanceResult" type="xsd:int"/>
  </message>

  <portType name="DistanceServiceSoapPort">
    <operation name="distance">
      <input message="tns:distance"/>
      <output message="tns:distanceResponse"/>
    </operation>
  </portType>

  <binding name="DistanceServiceSoapPort" type="tns:DistanceServiceSoapPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="distance">
      <soap:operation soapAction="distance"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="DistanceService">
    <documentation>WSDL File for HelloService</documentation>
    <port binding="tns:DistanceServiceSoapPort" name="DistanceServiceSoapPort">
      <soap:address location="http://localhost:8080/distance?wsdl" />
    </port>
  </service>
</definitions>